animals = ['bear', 'ruby', 'peacock', 'kangaroo', 'whale', 'platypus']
bear = animals[0]
peacock = animals[2]
bear = animals[0]
kangaroo = animals[3]
whale = animals[4]
peacock = animals[2]
platypus = animals[5]
whale = animals[4]

places = ['Seattle', 'Boston', 'Chicago', 'New York']
new york = places[3]
seattle = places[0]
chicago = places[2]

book_genres = ['nonfic', 'fic', 'YA', 'horror', 'mystery', 'memoir', 'sci-fi']
mystery = book_genres[4]
horror = book_genres[3]
ya = book_genres[2]
nonfic = book_genres[0]
fic = book_genres[1]
